version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: excel_db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    # volumes:
    #   - db_data:/var/lib/mysql

  app:
    build: 
      context: . 
      dockerfile: dockerfile 
    container_name: python_app
    environment:
      DB_HOST: localhost
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: excel_db
    ports:
      - "5000:5000"
    # volumes:
    #   - .:/app
    depends_on:
      - db

# volumes:
#   db_data:
